// PostList
export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const INVALIDATE_POSTS = 'INVALIDATE_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const HANDLE_DELETE_POST = 'HANDLE_DELETE_POST';
export const INVALIDATE_DELETE_POST = 'INVALIDATE_DELETE_POST';

// Form
export const UPDATE_POST = 'UPDATE_POST';
export const HANDLE_UPDATE_POST = 'HANDLE_UPDATE_POST';
export const INVALIDATE_UPDATE_POST = 'INVALIDATE_UPDATE_POST';

// PostDetails
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const RECEIVE_SINGLE_POST = 'RECEIVE_SINGLE_POST';
export const INVALIDATE_SINGLE_POST = 'INVALIDATE_SINGLE_POST';
export const FETCH_USERS = 'FETCH_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const INVALIDATE_USERS = 'INVALIDATE_USERS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const INVALIDATE_COMMENTS = 'INVALIDATE_COMMENTS';